name: Deploy Site

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '.github/**' # Ignore changes towards the .github directory
    branches:
    - master # Only trigger on the development branch

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
    
    - name: Install
      run: npm install

    - name: Build
      run: npm run dist

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
